name: Build and push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONTEXT_DIR: Sources
  IMAGE_TAG: v1.1
  DOCKERFILE: Dockerfile
  DOCKER_NAMESPACE: bvdcode
  DOCKER_IMAGE_NAME: mattermost-real-retention

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    outputs:
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: 5.x
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.11
        id: gitversion # step id used as reference for output values
      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.CONTEXT_DIR }}/${{ env.DOCKERFILE }}

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: ${{ env.CONTEXT_DIR }}/${{ env.DOCKERFILE }}

      - name: Create Release
        if: 1 == 0 #needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.Version }}
          release_name: Release ${{ needs.build.outputs.Version }}
      - name: Create Release
        if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.Version }}
          name: Release ${{ needs.build.outputs.Version }}
          artifacts: "nupkg/*"
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
